const CatDict = {
  "cp,sp": "Mobile Phones",
  "l,d": "Computers",
  "t,i": "Tablets & Ipads",
  "ca,pa,h&h ,oa": "Accessories",
  "mc,wc,kc": "Clothing",
  "ms,ws,s,a": "Shoes & Accessories",
  "f,b,ka,h&d": "Home & Kitchen",
  "hc,sc": "Beauty & Care",
  "bc,mg": "Grooming & Wellness",
  "fe,sg": "Fitness & Sports",
  "og,sw": "Outdoor and Wears",
  "af,et": "Toys",
  "bg,vg": "Games",
  "bm": "Books & Media",
  "fp,bv,sk": "Groceries & Refreshments",
  "hhs": "Hosusehold Essentials",
  "mds,fc": "Health Care",
  "ca,t&e": "Automobile",
  "pf,pt": "Pet Essentials",
  "gs,phr": "Grooming & Habitat",
  "stat,of": "Office",
  "cp": "Cell Phones",
  "sp": "Smartphones",
  "l": "Laptops",
  "d": "Desktops",
  "t": "Tablets",
  "i": "Ipads",
  "ca": "Computer Accessories",
  "pa": "Phone Accessories",
  "h&h": "Headphones & Headsets",
  "oa": "Other Accessories",
  "mc": "Men's Clothing",
  "wc": "Women's Clothing",
  "kc": "Kid's Clothing",
  "ms": "Men's Shoes",
  "ws": "Women's Shoes",
  "s": "Sneakers",
  "a": "Accessories",
  "f": "Furniture",
  "b": "Bedding",
  "ka": "Kitchen Accessories",
  "h&d": "Home and Decor",
  "hc": "Haircare",
  "sc": "Skincare",
  "mu": "MakeUp",
  "fg": "Fragrance",
  "bc": "Body Care",
  "mg": "Men's Grooming",
  "fe": "Fitness Equipments",
  "sg": "Sports Gears",
  "og": "Outdoor Gears",
  "sw": "Sports Wear",
  "af": "Action Figures",
  "et": "Educational toys",
  "bg": "Boarad Games",
  "vg": "Video Games",
  "fp": "Fresh Produce",
  "bv": "Beverages",
  "sk": "Snacks",
  "hhs": "Household Supplies",
  "meds": "Medical Supplies",
  "fc": "Feminie Care",
  "ca": "Car Accessories",
  "t&e": "Tools & Equipments",
  "pf": "Pet Food",
  "pt": "Pet Toys",
  "gs": "Grooming Supplies",
  "phr": "Pet habitat & grooming",
  "stat": "Stationery",
  "of": "Office Furniture",
};

export default CatDict;
